from .scrape_utils import get_modules
from .scrape_parallel import products_websites_sync as scrape_products_parallel
from .scrape_selenium import products_websites_selenium as scrape_products_selenium
